apiVersion: v1
kind: ServiceAccount
metadata:
  name: observability-reader
  namespace: observability
  labels:
    app.kubernetes.io/name: enterprise-observability
    app.kubernetes.io/component: rbac
