apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-web-ingress
  namespace: enterprise-landing-zone
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: enterprise-landing-zone.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: enterprise-web-service
                port:
                  number: 80
