apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: enterprise-web-pdb
  namespace: enterprise-landing-zone
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: enterprise-web
