apiVersion: v1
kind: ServiceAccount
metadata:
  name: enterprise-web-sa
  namespace: enterprise-landing-zone
  labels:
    app.kubernetes.io/name: enterprise-web
    app.kubernetes.io/component: serviceaccount
automountServiceAccountToken: false
